### PR TITLE
Typo on README.md

### PR DESCRIPTION
**Pull request by joelr**

### CODE REVIEW

**Comment by dadoonet** [comment]
Thank you!
Although it's a small change, would you mind signing the CLA so we can pull your change in?

**Comment by joelr** [comment]
@dadoonet done!

**Comment by dadoonet** [comment]
Great. Thank you!

**Comment by Tenzil** [comment]
@joelr @dadoonet  
 I couldn't install ICU plugin. Sorry to post it here
curl -XGET 'localhost:9200'
{
"name" : "D'Spayre",
"cluster_name" : "elasticsearch",
"version" : {
"number" : "2.3.1",
"build_hash" : "bd980929010aef404e7cb0843e61d0665269fc39",
"build_timestamp" : "2016-04-04T12:25:05Z",
"build_snapshot" : false,
"lucene_version" : "5.5.0"
},
"tagline" : "You Know, for Search"
}

sudo bin/plugin install elasticsearch/elasticsearch-analysis-icu/2.7.0
-> Installing elasticsearch/elasticsearch-analysis-icu/2.7.0...
Trying https://download.elastic.co/elasticsearch/elasticsearch-analysis-icu/elasticsearch-analysis-icu-2.7.0.zip ...
Downloading ............................DONE
Verifying https://download.elastic.co/elasticsearch/elasticsearch-analysis-icu/elasticsearch-analysis-icu-2.7.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip
webonise@webonise-Desktop:/usr/share/elasticsearch$ sudo bin/plugin --install elasticsearch/elasticsearch-analysis-icu/2.7.0
ERROR: unknown command [--install]. Use [-h] option to list available commands

**Comment by dadoonet** [comment]
Read: https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu.html

**Comment by Tenzil** [comment]
@dadoonet Thanks. Sorry once again

**Pull request merged**
